[project]
name = "model"
version = "0.1.0"
description = ""
requires-python = ">=3.12"
dependencies = [
    "lightgbm>=4.5.0",
    "notebook>=7.2.2",
    "optuna-integration[lightgbm]>=4.0.0",
    "optuna>=4.0.0",
    "pandas>=2.2.3",
    "scikit-learn>=1.5.2",
]
